export {default as About} from './about/About'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as Skills} from './skills/Skills'
export {default as Testimonial} from './testimonial/Testimonial'
export {default as Work} from './work/Work'